### ISSUE TITLE
Make icons easier to consume with a dist folder

### ISSUE THREAD

**Issue by barlock** [IBM-Design/icons#1]
Or something similar. In its current state the svgs aren't the easiest to consume. It would be great to have some kind of dist that put the svgs into a single folder (hopefully) and already minified. We could create various sprite sheets/icon fonts of all the icons to be easily consumable as well. Would you take a PR for this?

**Comment by Snugug** [comment]
IMO these should be treated as source files and have a build process actually pull in and turn them in to production items (minify/sprite sheet/etc). Especially true for icon fonts, where you absolutely don't want to use every icon in a font in production. Then there is the problem of using different sized icons for different needs that need to be taken in to account.

**Comment by barlock** [comment]
Sure, we could have a build process check the dist back into another branch other than master that we use to deploy to bower/npm (or another project whichever). We can probably intelligently architect the way the dist should look. I'm all for performance but "forcing" every project to write their own build scripts for the icon set seems a little much. Having the build code in the project would make it easier for consumers to adapt to their own needs as well.

**Comment by tkrugg** [comment]
We've solved this problem with a requirejs plugin.

**Comment by barlock** [comment]
Would you be open to generating a dist as a deploy step to npm/bower? Should be easily automate-able  via travis on a release trigger.

**Comment by tkrugg** [comment]
@Snugug if AMD is already part of your workflow, you might want to have a look at our solution to the problem: https://github.com/ibm-js/requirejs-dplugins/blob/master/docs/svg.md

**Comment by barlock** [comment]
I've realized that the only real source file are the illustrator files. The rest are generated and we should present the project as such. We can't guarantee at any new version of the icon that any previous change made to the svg will be there.

I think it makes the most sense to put all the svg s and png into a dist folder and automate the export from illustrator with any repeatable transformations to the svgs that developers need. (For example with a gulp task). That way we can ensure a consistent svg "api". 

I think that with the new glyphs would be a good candidate for 2.0.0... The current 1.1 has breaking api changes and I don't think it's safe to deploy that to npm or bower.

**Comment by barlock** [comment]
@mil How do you feel about the proposed layout for `2.0.0`? I'll submit a pr with it those changes laid out in a bit.

**Comment by mil** [comment]
@mbarlock:
Automating the svg/png export and additionally adding in the new glyphs for a 2.0.0 seems in-line. Also I agree that our build scripts being part of the repo as being the way forward.

**Comment by barlock** [comment]
The big change that I was thinking about was a folder structure change

```
dist
| -- svg
| -- png
src
| -- 
    | -- object-based.ai
    | -- the rest of the illustrator files
package.json
bower.json
gulpfile.js (for automation)
```

I want to create this distinction so its obvious people know that the svgs and pngs are generated and updating them without a gulp script wont fly.

**Comment by barlock** [comment]
@mil I made a pr to show the document structure I'm proposing. Merge if you like it.
