### ISSUE TITLE
Inconsistencies in SVG markup

### ISSUE THREAD

**Issue by tkrugg** [IBM-Design/icons#3]
SVGs unconsistently have background-icon-guides layers `<g>` or nothing.

See for example: 
- https://raw.githubusercontent.com/IBM-Design/icons/master/svg/object-based/activity_128.svg
- https://raw.githubusercontent.com/IBM-Design/icons/master/svg/glyphs/chat_24.svg

**Comment by jhnsnc** [comment]
Inconsistencies and other issues I've noticed:
- sporadic line breaks in path data
- graphics groups that are completely hidden (and therefore completely wasted filesize)
- unnecessary attributes on tags
- unnecessary nesting of graphic groups
- groups containing only one path
- duplicated path elements (e.g. 2 <polygon>s in the same file both with the same path data)

I'm working on a cleanup PR to fix these problems and generally optimize the SVG assets.

**Comment by barlock** [comment]
Fixed by #34
