### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by kevinSuttle** [IBM-Design/icons#45]
I've seen this done as a bell, as it is here on GitHub. Seems to work well. Has a dot on it when there is new activity, but I'd prefer a number. Either way.

**Comment by kevinSuttle** [comment]
I know there's Announcement, but that's not quite it. I could be convinced though. https://www.ibm.com/design/language/resources/icon-library/downloads/ibm-design-icons-announcement.zip

**Comment by brianburnette** [comment]
We're testing a banner notification in our product now that works like....
![bannernotifications](https://cloud.githubusercontent.com/assets/13439551/13824948/90175e96-eb86-11e5-9409-c5ab7dd33a15.PNG)

**Comment by barlock** [comment]
@brianburnette could you make a pr with the illustrator files for the belll?
