### ISSUE TITLE
Android and iOS app icons templates

### ISSUE THREAD

**Issue by kevinSuttle** [IBM-Design/icons#59]
Wondering if we have these somewhere and just aren't linking them. 
https://www.ibm.com/design/language/resources/

**Comment by seejamescode** [comment]
Are you seeking a certain file type of the existing icons?
Or a starter template when making an IBM native app icon?

**Comment by kevinSuttle** [comment]
The latter

**Comment by seejamescode** [comment]
I do not believe this is within the scope of this repo, but a great idea!
