### ISSUE TITLE
Bee 16’s wings are asymmetrical

### ISSUE THREAD

**Issue by briandrum** [IBM-Design/icons#60]
While performing some optimizations with SVGO, I noticed that little bee's wings are not symmetrical. I believe the right wing is correct.

![bee_16](https://cloud.githubusercontent.com/assets/114522/20396573/a334933c-acb4-11e6-883f-c5e73c21e0ea.png)

**Comment by seejamescode** [comment]
Thanks for catching it! Would you be able to submit this file fixed? https://github.com/IBM-Design/icons/blob/master/src/object-based/bee.ai
