### ISSUE TITLE
Link on main page is broken...

### ISSUE THREAD

**Issue by owendall** [IBM-Design/icons#64]

**Comment by owendall** [comment]
![image](https://cloud.githubusercontent.com/assets/10927/22110499/e990ccf0-de29-11e6-8a3d-7bce8fdc9679.png)

**Comment by matthewgallo** [comment]
Hi @owendall, thanks for posting here about it. I haven't been able to replicate the 404. Are you still experience this issue at all?

**Comment by seejamescode** [comment]
Closing until further clarification
