### ISSUE TITLE
Submitting glyphs for get-information icon

### ISSUE THREAD

**Issue by lehelbabos** [IBM-Design/icons#66]
I've created 16px/24px glyphs for the info icon. Submitting for review. 

Saved icon file out as a PDF since github won't let me upload SVGs / AIs.

Happy to answer any questions or make any revisions.

[get-information icon.pdf](https://github.com/IBM-Design/icons/files/839704/get-information.icon.pdf)

**Comment by barlock** [comment]
Could you zip the .ai and send that?

**Comment by lehelbabos** [comment]
Attached
[get-information.ai.zip](https://github.com/IBM-Design/icons/files/841529/get-information.ai.zip)

**Comment by barlock** [comment]
**CC: @hchughes @seejamescode**

**Comment by seejamescode** [comment]
@evanmaeda, was there a reason we left out glyphs for this? If not, any visual feedback?

**Comment by seejamescode** [comment]
Emailed @hchughes with the zip for review now

**Comment by lehelbabos** [comment]
Any progress on this? @seejamescode @hchughes

**Comment by hchughes11** [comment]
These submissions can be merged into the icon repo. They are approved for use.
