### ISSUE TITLE
Missing SVGs for download icon

### ISSUE THREAD

**Issue by samjsmith** [IBM-Design/icons#67]
I can't see files for download_16.svg or download_24.svg.
Are they supposed to be created?

**Comment by barlock** [comment]
@samjsmith Actually no! There are not glyphs for all of the icons. `download` in particular only has 32, 64, and 128. You can tell for any icon by going into the source and looking at the artboards

![image](https://cloud.githubusercontent.com/assets/5770007/23901671/ab4e4f86-0894-11e7-9eb3-02207f349ff7.png)

If you can fill in the missing glyphs a pull request would be appreciated.

**Comment by seejamescode** [comment]
Thanks @mbarlock!
